FileVersion = 1
Dependencies = {corlib = "*", BJSON = "*"}

[Project]
Name = "BJSON.Test"
TargetType = "BeefTest"
StartupObject = "BJSON.Test.Program"

[Configs.Test.Win64]
BeefLibType = "DynamicDebug"
PostBuildCmds = ["CopyFilesIfNewer(\"$(ProjectDir)/test_files/*\", \"$(BuildDir)/test_files\")"]

[[Configs.Test.Win64.DistinctOptions]]
Filter = ""
